pipeline {
    agent {
        label 'master'
    }
    options {
        gitLabConnection('git.sami.int.thomsonreuters.com')
        disableConcurrentBuilds()
        timeout(time: 20, unit: 'MINUTES')
        timestamps()
    }
    environment {
    }
    triggers {
        gitlab( triggerOnPush: true, 
                triggerOnMergeRequest: true, 
                branchFilterType: 'NameBasedFilter',
                skipWorkInProgressMergeRequest: true,
                ciSkip: true,
                setBuildDescription: true)
    }
    stages {
        stage('Build Docker Image') {
            steps {
               echo "Build docker image"
            }
        }
        stage('Push to BAMS') {
            steps {
                echo 'Push Docker Image to BAMS..'
            }
        }
    }
}